/// Generated by AssetsRefGenerator on 2021/01/24
class Res {
  static const String amazon = "assets/images/amazon.png";
  static const String amazon_pay = "assets/images/amazon_pay.png";
  static const String cart_empty_state = "assets/images/cart_empty_state.png";
  static const String cash_on_delivery = "assets/images/cash_on_delivery.png";
  static const String credit_card = "assets/images/credit_card.png";
  static const String debit_card = "assets/images/debit_card.png";
  static const String facebook = "assets/images/facebook.png";
  static const String google_pay = "assets/images/google_pay.png";
  static const String instagram = "assets/images/instagram.png";
  static const String linkedin = "assets/images/linkedin.png";
  static const String logo = "assets/images/logo.jpeg";
  static const String logo_old = "assets/images/logo_old.jpeg";
  static const String myaccount_emptystate = "assets/images/myaccount_emptystate.png";
  static const String netbanking = "assets/images/netbanking.png";
  static const String order_empty_state = "assets/images/order_empty_state.png";
  static const String paytm = "assets/images/paytm.png";
  static const String pone_pe = "assets/images/pone_pe.png";
  static const String search_result_not_match = "assets/images/search_result_not_match.png";
  static const String something_went_wrong_empty_state = "assets/images/something_went_wrong_empty_state.png";
  static const String twitter = "assets/images/twitter.png";
  static const String upi = "assets/images/upi.png";
  static const String wallet = "assets/images/wallet.png";
  static const String whatsapp = "assets/images/whatsapp.png";
  static const String wishlist_empty_state = "assets/images/wishlist_empty_state.png";
}
