/// Generated by AssetsRefGenerator on 2021/01/10
class Res {
  static const String cart_empty_state = "assets/images/cart_empty_state.png";
  static const String logo = "assets/images/logo.jpeg";
  static const String logo_old = "assets/images/logo_old.jpeg";
  static const String order_empty_state = "assets/images/order_empty_state.png";
  static const String search_result_not_match = "assets/images/search_result_not_match.png";
  static const String something_went_wrong_empty_state = "assets/images/something_went_wrong_empty_state.png";
  static const String wishlist_empty_state = "assets/images/wishlist_empty_state.png";
}
